"""Generic script template for Alembic migrations.

DO NOT EDIT THIS FILE -- edit alembic/versions scripts instead.
"""
from alembic import op
import sqlalchemy as sa


def upgrade():
    pass


def downgrade():
    pass
